### ISSUE TITLE
use of async functions instead of callbacks

### ISSUE THREAD

**Issue by brianmay** [frawau/aiolifx#18]
Hello,

I created a fork of aiolifx that replaces the many callbacks with Python 3.5 style async functions - instead of callback functions, which better suit my needs.

https://github.com/frawau/aiolifx/compare/master...brianmay:async_functions

As this means significant incompatible changes to the API, and also drops Python 3.4 support, I suspect you might be reluctant to merge my changes. Hence I plan to continue this fork - possibly under a new - yet-to-be-determined name and will make unrelated changes such as making the code base PEP8 compliant.

I thought I should let you know of my plans.

Feel free to close this issue report.

Regards

**Comment by brianmay** [comment]
The problems in #17 are part of my motivation with this. With proper async functions, we can await on the function call and know that we have a response when the await completes.

**Comment by frawau** [comment]
I personally prefer the callback way, but ...  whatever works for you.

aiolifx is used with Home Assistant, so I can't drop the 3.4 support

Cheers
