### ISSUE TITLE
Is everything ok?

### ISSUE THREAD

**Issue by Djelibeybi** [frawau/aiolifx#56]
I just wanted to check-in because usually you're really responsive with reviewing issues and PRs. With one PR hitting almost a month without comment, I'm just a bit concerned.

**Comment by frawau** [comment]
Yes I am OK. Thanks for your concern.  I just had a long holiday away from my computer.

**Comment by frawau** [comment]
Before I push a new version, I want to get rid of a deprecation  in the script. Will probably have to wait for the WE

**Comment by Djelibeybi** [comment]
No worries.
