### ISSUE TITLE
Add LICENSE.txt to PyPi tarball

### ISSUE THREAD

**Issue by bachp** [frawau/aiolifx#8]
This makes it easier to package this for distributions.

**Comment by frawau** [comment]
Not sure what you mean...
 ==> tar tvfz 0.4.6.tar.gz 
drwxrwxr-x root/root         0 2017-04-28 11:20 aiolifx-0.4.6/
-rw-rw-r-- root/root      1085 2017-04-28 11:20 aiolifx-0.4.6/LICENSE.txt
-rw-rw-r-- root/root      2934 2017-04-28 11:20 aiolifx-0.4.6/README.md
drwxrwxr-x root/root         0 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/
-rw-rw-r-- root/root       709 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/CHANGES.txt
-rw-rw-r-- root/root       214 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/__init__.py
-rw-rw-r-- root/root      7904 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/__main__.py
-rw-rw-r-- root/root     27515 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/aiolifx.py
-rw-rw-r-- root/root     27549 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/aiolifx34.py
-rw-rw-r-- root/root      6762 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/message.py
-rw-rw-r-- root/root     29140 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/msgtypes.py
-rw-rw-r-- root/root      1512 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/products.py
-rw-rw-r-- root/root     12817 2017-04-28 11:20 aiolifx-0.4.6/aiolifx/unpack.py
drwxrwxr-x root/root         0 2017-04-28 11:20 aiolifx-0.4.6/examples/
-rw-rw-r-- root/root      7904 2017-04-28 11:20 aiolifx-0.4.6/examples/lifx-cli.py
-rw-rw-r-- root/root        39 2017-04-28 11:20 aiolifx-0.4.6/setup.cfg
-rw-rw-r-- root/root      1016 2017-04-28 11:20 aiolifx-0.4.6/setup.py

It is there .....

**Comment by bachp** [comment]
If you download [aiolifx-0.4.6.tar.gz](https://pypi.python.org/packages/86/31/55192e4e0167d126961cb05e43693ba15eda885e3dcbf76f4e8c57f55f36/aiolifx-0.4.6.tar.gz#md5=d36cd6a3bb9d9ef6631b7dff535ef2b8) from https://pypi.python.org/pypi/aiolifx/0.4.6 and check he content there is no LICENSE.txt file.

**Comment by bachp** [comment]
BTW I think the solution is to add a [MANIFEST.in](https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute) file. Like [aiohttp](https://github.com/aio-libs/aiohttp/blob/master/MANIFEST.in) for example.

**Comment by frawau** [comment]
I see.  Thanks for the info. The license file will be included next time I release aiolifx.
